/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/9.0.39 (8.0.5)
 * Generated at: 2020-12-08 05:40:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import myPackage.classes.Exams;
import myPackage.classes.Questions;
import java.util.ArrayList;

public final class exam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("myPackage.classes.Questions");
    _jspx_imports_classes.add("myPackage.classes.Exams");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      myPackage.DatabaseClass pDAO = null;
      pDAO = (myPackage.DatabaseClass) _jspx_page_context.getAttribute("pDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (pDAO == null){
        pDAO = new myPackage.DatabaseClass();
        _jspx_page_context.setAttribute("pDAO", pDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("\n");
      out.write("<!-- SIDEBAR -->\n");
      out.write("\t\t\t<div class=\"sidebar\" style=\"background-image: url(sidebar-1.jpg)\">\n");
      out.write("\t\t\t\t<div class=\"sidebar-background\" >\n");
      out.write("\t\t\t\t\t<h2 class=\"logo-text\">\n");
      out.write("\t\t\t\t\t\tOnline Examination System\n");
      out.write("\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t<div class=\"left-menu\">\n");
      out.write("\t\t\t\t\t\t<a  href=\"std-page.jsp?pgprt=0\"><h2>Profile</h2></a>\n");
      out.write("\t\t\t\t\t\t<a class=\"active\" href=\"std-page.jsp?pgprt=1\"><h2>Exams</h2></a>\n");
      out.write("\t\t\t\t\t\t<a  href=\"std-page.jsp?pgprt=2\"><h2>Results</h2></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("                       </div>\n");
      out.write("               <!-- CONTENT AREA -->\n");
      out.write("\t\t\t<div class=\"content-area\">\n");
      out.write("                            \n");
      out.write("                               \n");
      out.write("    ");
 if(session.getAttribute("examStarted")!=null){ 
      out.write(" \n");
      out.write("    \n");
      out.write("    ");
 }
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("        ");

           if(session.getAttribute("examStarted")!=null){
               if(session.getAttribute("examStarted").equals("1")){
                
      out.write("\n");
      out.write("                <span id=\"remainingTime\" style=\"position: fixed;top:90px;left: 300px;font-size: 23px;background: rgba(255,0,77,0.38);border-radius: 5px;padding: 10px;box-shadow: 2px -2px 6px 0px;\">\n");
      out.write("        </span>\n");
      out.write("                   \n");
      out.write("                    <script>\n");
      out.write("                        var time = ");
      out.print(pDAO.getRemainingTime(Integer.parseInt(session.getAttribute("examId").toString())) );
      out.write(";\n");
      out.write("    time--;\n");
      out.write("    var sec=60;                    \n");
      out.write("    document.getElementById(\"remainingTime\").innerHTML =  time+\" : \"+sec;\n");
      out.write("       //it calls fuction after specific time again and again                  \n");
      out.write("   var x= window.setInterval(timerFunction, 1000);\n");
      out.write("\n");
      out.write("function timerFunction(){\n");
      out.write("        sec--;\n");
      out.write("  // Display the result in the element with id=\"demo\"\n");
      out.write("  \n");
      out.write(" \n");
      out.write("  if (time < 0) {\n");
      out.write("    clearInterval(x);\n");
      out.write("    document.getElementById(\"remainingTime\").innerHTML = \"00 : 00\";\n");
      out.write("    document.getElementById(\"myform\").submit();\n");
      out.write("  }\n");
      out.write("  document.getElementById(\"remainingTime\").innerHTML =  time+\" : \"+sec;\n");
      out.write("if(sec==0){\n");
      out.write("    sec=60;\n");
      out.write("    time--;\n");
      out.write("    \n");
      out.write("}\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("               <form id=\"myform\" action=\"controller.jsp\">\n");
      out.write("                       \n");
      out.write("                       ");

                       ArrayList list=pDAO.getQuestions(request.getParameter("coursename"),20);
                       Questions question;
                       
      out.write("\n");
      out.write("                       <input type=\"hidden\" name=\"size\" value=\"");
      out.print(list.size());
      out.write("\">\n");
      out.write("                       <input type=\"hidden\" name=\"totalmarks\" value=\"");
      out.print(pDAO.getTotalMarksByName(request.getParameter("coursename")));
      out.write("\">\n");
      out.write("                       \n");
      out.write("                       ");

                       for(int i=0;i<list.size();i++){
                           question=(Questions)list.get(i);
                       
      out.write("\n");
      out.write("         \n");
      out.write("                       \n");
      out.write("                       <center>\n");
      out.write("\t\t\t\t\t<div class=\"question-panel\">\n");
      out.write("\t\t\t\t\t\t<div class=\"question\" >\n");
      out.write("\t\t\t\t\t\t<label class=\"question-label\">");
      out.print(i+1 );
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t");
      out.print(question.getQuestion() );
      out.write("\n");
      out.write("                                                </div>\n");
      out.write("\t\t\t\t\t\t<div class=\"answer\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"c1");
      out.print(i);
      out.write("\" name=\"ans");
      out.print(i);
      out.write("\" value=\"");
      out.print(question.getOpt1());
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t\t<label for=\"c1");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(question.getOpt1());
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"c2");
      out.print(i);
      out.write("\" name=\"ans");
      out.print(i);
      out.write("\" value=\"");
      out.print(question.getOpt2());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t<label for=\"c2");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(question.getOpt2());
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" id=\"c3");
      out.print(i);
      out.write("\" name=\"ans");
      out.print(i);
      out.write("\" value=\"");
      out.print(question.getOpt3());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t<label for=\"c3");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(question.getOpt3());
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\"  id=\"c4");
      out.print(i);
      out.write("\" name=\"ans");
      out.print(i);
      out.write("\" value=\"");
      out.print(question.getOpt4());
      out.write("\"/>\n");
      out.write("\t\t\t\t\t\t\t<label for=\"c4");
      out.print(i);
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(question.getOpt4());
      out.write("</label>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("                       <input type=\"hidden\" name=\"question");
      out.print(i);
      out.write("\" value=\"");
      out.print(question.getQuestion());
      out.write("\">\n");
      out.write("                       <input type=\"hidden\" name=\"qid");
      out.print(i);
      out.write("\" value=\"");
      out.print(question.getQuestionId());
      out.write("\">\n");
      out.write("                       \n");
      out.write("                       \n");
      out.write("                       \n");
      out.write("                       ");

                       }
                       
                       
      out.write("\n");
      out.write("                       \n");
      out.write("                       \n");
      out.write("                   <input type=\"hidden\" name=\"page\" value=\"exams\">\n");
      out.write("                   <input type=\"hidden\" name=\"operation\" value=\"submitted\"> \n");
      out.write("                   <input type=\"submit\" class=\"add-btn\" value=\"Done\">\n");
      out.write("               </form>\n");
      out.write("               \n");
      out.write("               \n");
      out.write("                \n");
      out.write("                ");

               }
           }else if(request.getParameter("showresult")!=null){
               if(request.getParameter("showresult").equals("1")){
                  Exams result= pDAO.getResultByExamId(Integer.parseInt(request.getParameter("eid")));
           
      out.write("\n");
      out.write("           <div class=\"panel\" style=\"float: left;max-width: 900px\">\n");
      out.write("           <div class=\"title\">Result of Recent Exam</div>\n");
      out.write("           <div class=\"profile\">\n");
      out.write("               <span class=\"tag\">Exam Date</span><span class=\"val\">");
      out.print(result.getDate() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Start Time</span><span class=\"val\">");
      out.print(result.getStartTime() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">End Time</span><span class=\"val\">");
      out.print(result.getEndTime() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Course Name</span><span class=\"val\">");
      out.print(result.getcName() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Obt Marks</span><span class=\"val\">");
      out.print(result.getObtMarks() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Total Marks</span><span class=\"val\">");
      out.print(result.gettMarks() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Result</span><span class=\"val\">");
      out.print(result.getStatus() );
      out.write("</span></h2>\n");
      out.write("           </div>\n");
      out.write("           <p></p>\n");
      out.write("           <p></p>\n");
      out.write("           <p></p>\n");
      out.write("           <p></p>\n");
      out.write("           <p></p>\n");
      out.write("           </div>\n");
      out.write("           ");

           }
           }else if(session.getAttribute("examStarted")==null ){
        
      out.write("\n");
      out.write("        <div class=\"panel form-style-6\" style=\"float: left;max-width: 900px; padding-top: 40px;\">\n");
      out.write("            <div class=\"title\" style=\"margin-top: -60px;\">Select Course to Take Exam</div>\n");
      out.write("       <br/>\n");
      out.write("           \n");
      out.write("               <form action=\"controller.jsp\">\n");
      out.write("                   <br/><br>\n");
      out.write("                <label>Select Course</label>\n");
      out.write("                <input type=\"hidden\" name=\"page\" value=\"exams\">\n");
      out.write("                <input type=\"hidden\" name=\"operation\" value=\"startexam\">\n");
      out.write("                <select name=\"coursename\" class=\"text\">\n");
      out.write("        ");
 
            ArrayList list1=pDAO.getAllCourses();
            
            for(int i=0;i<list1.size();i=i+2){
        
      out.write("\n");
      out.write("        <option value=\"");
      out.print(list1.get(i));
      out.write('"');
      out.write('>');
      out.print(list1.get(i));
      out.write("</option>\n");
      out.write("            ");

            }
            
      out.write("\n");
      out.write("            </select>\n");
      out.write("            <input type=\"submit\" value=\"Take Exam\" class=\"form-button\">\n");
      out.write("            </form>\n");
      out.write("         \n");
      out.write("        </div>\n");
      out.write("       ");
 }
      out.write("\n");
      out.write("    \n");
      out.write("</div>\n");
      out.write("       ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
