/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/9.0.39 (8.0.5)
 * Generated at: 2020-12-08 05:39:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import myPackage.classes.User;
import java.util.ArrayList;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("myPackage.classes.User");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      myPackage.DatabaseClass pDAO = null;
      pDAO = (myPackage.DatabaseClass) _jspx_page_context.getAttribute("pDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (pDAO == null){
        pDAO = new myPackage.DatabaseClass();
        _jspx_page_context.setAttribute("pDAO", pDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      out.write('\n');

           User user=pDAO.getUserDetails(session.getAttribute("userId").toString());
           if(user.getType().endsWith("admin")){
        
      out.write("\n");
      out.write("         <!-- SIDEBAR -->\n");
      out.write("\t\t\t<div class=\"sidebar\" style=\"background-image: url(sidebar-1.jpg)\">\n");
      out.write("\t\t\t\t<div class=\"sidebar-background\" >\n");
      out.write("\t\t\t\t\t<h2 class=\"logo-text\">\n");
      out.write("\t\t\t\t\t\tOnline Examination System\n");
      out.write("\t\t\t\t\t</h2>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"left-menu\">\n");
      out.write("\t\t\t\t\t\t<a class=\"active\" href=\"adm-page.jsp?pgprt=0\"><h2>Profile</h2></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"adm-page.jsp?pgprt=2\"><h2>Courses</h2></a>\n");
      out.write("                                                <a href=\"adm-page.jsp?pgprt=3\"><h2>Questions</h2></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"adm-page.jsp?pgprt=1\"><h2>Accounts</h2></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("            <!-- CONTENT AREA -->\n");
      out.write("\t\t\t<div class=\"content-area\">\n");
      out.write("                            <div class=\"panel\" style=\"float: left;max-width: 600px\">\n");
      out.write("        \n");
      out.write("                                \n");
      out.write("        \n");
      out.write("            ");

           }else{
               
      out.write("\n");
      out.write("               \n");
      out.write("               <!-- SIDEBAR -->\n");
      out.write("\t\t\t<div class=\"sidebar\" style=\"background-image: url(sidebar-1.jpg)\">\n");
      out.write("\t\t\t\t<div class=\"sidebar-background\" >\n");
      out.write("\t\t\t\t\t<h2 class=\"logo-text\">\n");
      out.write("\t\t\t\t\t\tOnline Examination System\n");
      out.write("\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t<div class=\"left-menu\">\n");
      out.write("\t\t\t\t\t\t<a class=\"active\" href=\"std-page.jsp?pgprt=0\"><h2>Profile</h2></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"std-page.jsp?pgprt=1\"><h2>Exams</h2></a>\n");
      out.write("\t\t\t\t\t\t<a href=\"std-page.jsp?pgprt=2\"><h2>Results</h2></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("                       </div>\n");
      out.write("               <!-- CONTENT AREA -->\n");
      out.write("\t\t\t<div class=\"content-area\">\n");
      out.write("                            <div class=\"panel\" style=\"float: left;max-width: 600px\">\n");
      out.write("               ");

           }
           if(request.getParameter("pedt")==null){
           
      out.write("\n");
      out.write("           <div class=\"title\">Profile</div>\n");
      out.write("           <div class=\"profile \">\n");
      out.write("               <h2><span class=\"tag\">Your Name</span><span class=\"val\">");
      out.print(user.getFirstName()+" " );
      out.print(user.getLastName() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Email</span><span class=\"val\">");
      out.print(user.getEmail() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Contact No</span><span class=\"val\">");
      out.print(user.getContact() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">City</span><span class=\"val\">");
      out.print(user.getCity() );
      out.write("</span><br/>\n");
      out.write("               <span class=\"tag\">Address</span><span class=\"val\">");
      out.print(user.getAddress() );
      out.write("</span></h2>\n");
      out.write("           </div>\n");
      out.write("               ");

               if(user.getType().equals("admin")){
               
      out.write("\n");
      out.write("               <br/>\n");
      out.write("               <a href=\"adm-page.jsp?pgprt=0&pedt=1\"><span class=\"add-btn\">Edit Profile</span></a>\n");
      out.write("               ");
 
               }else{
               
      out.write("<br/>\n");
      out.write("               <a href=\"std-page.jsp?pgprt=0&pedt=1\"><span class=\"add-btn\">Edit Profile</span></a>\n");
      out.write("               ");
 
               }
               
      out.write("\n");
      out.write("           \n");
      out.write("           ");

           }else{
               
      out.write("\n");
      out.write("               \n");
      out.write("               <!-- Start of Edit Form --->\n");
      out.write("               <div class=\"title\">Edit Profile</div>\n");
      out.write("               <div class=\"central-div form-style-6\" style=\"position:inherit;margin-top: 70px;\" >\n");
      out.write("                    <form action=\"controller.jsp\">\n");
      out.write("                        <input type=\"hidden\" name=\"page\" value=\"profile\"> \n");
      out.write("                        <input type=\"hidden\" name=\"utype\" value=\"");
      out.print(user.getType());
      out.write("\">\n");
      out.write("\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>First Name</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"text\" name=\"fname\" value=\"");
      out.print(user.getFirstName() );
      out.write("\" class=\"text\" placeholder=\"First Name\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>Last Name</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"text\"  name=\"lname\" value=\"");
      out.print(user.getLastName() );
      out.write("\" class=\"text\" placeholder=\"Last Name\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>User Name</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"text\" name=\"uname\" value=\"");
      out.print(user.getUserName() );
      out.write("\" class=\"text\" placeholder=\"User Name\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>Email</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"email\" name=\"email\" value=\"");
      out.print(user.getEmail() );
      out.write("\" class=\"text\" placeholder=\"Email\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>Password</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"password\" value=\"");
      out.print(user.getPassword() );
      out.write("\" name=\"pass\" class=\"text\" placeholder=\"Password\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("                                        <tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>Contact No</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"text\" name=\"contactno\" value=\"");
      out.print(user.getContact() );
      out.write("\" class=\"text\" placeholder=\"Contact No\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("                                        <tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>City</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"text\" name=\"city\" value=\"");
      out.print(user.getCity() );
      out.write("\" class=\"text\" placeholder=\"City\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("                                        <tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<label>Address</label>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("                                                    <input type=\"text\" name=\"address\" value=\"");
      out.print(user.getAddress() );
      out.write("\" class=\"text\" placeholder=\"Address\">\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t<center>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Done\" class=\"button\">\n");
      out.write("\t\t\t\t\t\t\t</center>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("                \n");
      out.write("               ");

           }
           
      out.write("\n");
      out.write("    \n");
      out.write("        </div>\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
